apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-2-7b
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      runtime: kserve-tritonserver
      runtimeVersion: 23.10-vllm-python-py3
      storageUri: gs://kfserving-examples/models/triton/vllm/model_repository
      resources:
        limits:
          cpu: "4"
          memory: 10Gi
          #nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 10Gi
          #nvidia.com/gpu: "1"
